### PR TITLE
Fix Gloves

### PR DESCRIPTION
**Pull request by komashchenko**
Correction disappearance gloves 😀

### CODE REVIEW

**Comment by NapasP** [comment]
@Franc1sco up

**Comment by theelsaud** [comment]
@Franc1sco up, it's nice fix)

**Comment by pavelnaydyonov** [comment]
up

**Comment by paulocrash** [comment]
I don't believe he will accept this Pull Requests.

> Note: If you want to use a valve gloves plugin with this plugin you can use my valve gloves plugin that have support for my emotes plugin version.

http://prntscr.com/pseqru

Anyway, I hope I'm wrong. :wink:

**Comment by Franc1sco** [comment]
Just i dont like to add the dependency of a gamedata that could cause server crashes in future csgo updates just for a fix that is already implemented with a native and without a gamedata. But thanks anyway :wink:

**Pull request closed without merging**
